
services:
  - type: web
    plan: free
    name: queen-anju-md
    runtime: docker
    region: Frankfurt
    branch: main
    repo: https://github.com/Mrrashmika/QUEEN_ANJU_MD
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SESSION_ID
        value: "YOUR_SESSION_ID"
      - key: NODE_VERSION
        value: "20.x"
